config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users,only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :tweeeets

  root 'tweeeets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeeet.rb
class Tweeeet < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
has_many :Tweeeets
 	include Clearance::User
    	validates :username, presence: true, uniqueness: true 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
 
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index

	end

	
end

app/controllers/tweeeets_controller.rb
class TweeeetsController < ApplicationController
  before_action :set_tweeeet, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]
  # GET /tweeeets
  # GET /tweeeets.json
  def index
    @tweeeets = Tweeeet.all
    @tweeeet = Tweeeet.new
  end

  # GET /tweeeets/1
  # GET /tweeeets/1.json
  def show
  end

  # GET /tweeeets/new
  def new
    @tweeeet = current_user.Tweeeets.build
  end

  # GET /tweeeets/1/edit
  def edit
  end

  # POST /tweeeets
  # POST /tweeeets.json
  def create
    @tweeeet = current_user.Tweeeets.build(tweeeet_params)

    respond_to do |format|
      if @tweeeet.save
        format.html { redirect_to root_path, notice: 'Tweeeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeeet }
      else
        format.html { render :new }
        format.json { render json: @tweeeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeeets/1
  # PATCH/PUT /tweeeets/1.json
  def update
    respond_to do |format|
      if @tweeeet.update(tweeeet_params)
        format.html { redirect_to @tweeeet, notice: 'Tweeeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeeets/1
  # DELETE /tweeeets/1.json
  def destroy
    @tweeeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeeets_url, notice: 'Tweeeet was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeeet
      @tweeeet = Tweeeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeeet_params
      params.require(:tweeeet).permit(:tweeet)
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	private

	def user_params
		params.require(:user).permit(:name, :username, :email, :password)
			
	end		
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweeeets_helper.rb
module TweeeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    
  </head>
 
  <body>
     <% if signed_in? %>
    <header> 
    <nav class="navbar is-info">
      <%= link_to root_path, class: "navbar-item"  do %>
      <h1 class="title is-5"><i class="fa fa-twitter" ></i>  Twittter</h1> 
      <% end %>
    </header>
  <section>
      <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %> has-text-centered"><%= value %></div>
      <% end %>
      </div>
    </section>
  <%= yield %>
  <% else %>
 <header> 
    <nav class="navbar is-info">
      <%= link_to root_path, class: "navbar-item"  do %>
      <h1 class="title is-5"><i class="fa fa-twitter" ></i>  Twittter</h1> 
      <% end %> 
    <div class="Navbar-burger burger" data-target=" navbarExample">
    
    </div>
      <div id ="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
          <%= link_to 'Sign Up ', sign_up_path, class:"button is-info is-inverted is-mobile" %>
          
           <%= link_to 'Sign in', sign_in_path, class:"button is-info is-inverted is-mobile" %>
          </div>
        </div>
      </div>
    </nav>
    </header>
  <section>
      <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %> has-text-centered"><%= value %></div>
      <% end %>
      </div>
    </section> 
    
  <%= yield %>

 </body> 
<%end%> 

   
</html>

app/views/tweeeets/_feed.html.erb
<div class="container">
	<% if signed_in? %>
	 <div class="tab-content">
	 	<div class="tab-pane fade in active" id="foryou">
			<div class="column">
				<% if signed_in? %>
				<article class="media box">
					<figure class="media-left">
						<p class="image is-64x64">
							<img src="https://bulma.io/images/placeholders/64x64.png">
						</p>
					</figure>
					<div class="media-content"> 
						<%=render'tweeeets/form' %> 
					</div>
				</article>
				<%end%> 
			<% @tweeeets.each do | tweeet | %>
			<div class = "box">
				<article class="media">
					<div class="media-left">
						<figure class="image is-64x64">
							<img src="https://bulma.io/images/placeholders/64x64.png">
						</figure>
					</div>
					<div class="media-content">
						<div class="content">
							<strong><%= tweeet.user.name%> </strong> <br />
							<p> @<%= tweeet.user.username%> </p>
							<p> <%= tweeet.tweeet %> </p>
						</div>
						<nav class="level"> 
							<div class="level-left is-mobile">
								<%= link_to tweeet, class: "level-item" do%>
									<span class="icon"><i class="fa fa-link"></i></span>
								<% end %>	
								<%= link_to edit_tweeeet_path(tweeet), class: "level-item" do%>
									<span class="icon"><i class="fa fa-pencil"></i></span>
								<% end %>	
								<%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
									<span class="icon"><i class="fa fa-trash-o"></i></span>
								<% end %>	

							</div>
						</nav>

					</div>
				</article>
			</div>
			<% end %>
	 	</div>
	 </div>
	</div>
</div>

 <%else%>
 <div class="container">
 <ul class="nav nav-tabs"> 
 	<li class="active"> <a href="#foryou" data-toggle="tab">For you</a></li> 
 	<li > <a href="#trends" data-toggle="tab">Trending</a></li> 
 	<li > <a href="#news" data-toggle="tab">News</a></li> 
 	<li > <a href="#sports" data-toggle="tab">Sports</a></li> 
 	<li > <a href="#fun" data-toggee="tab">Fun</a></li> 
 	<li > <a href="#enter" data-toggle="tab">Entertainment</a></li> 
 </ul>
	<div class="column">
	<% @tweeeets.each do | tweeet | %>
	<div class = "box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64x64">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong><%= tweeet.user.name%> </strong> <br />
					<p> @<%= tweeet.user.username%> </p>
					<p> <%= tweeet.tweeet %> </p>
				</div>
				<nav class="level"> 
					<div class="level-left is-mobile">
						<%= link_to tweeet, class: "level-item" do%>
							<span class="icon"><i class="fa fa-link"></i></span>
						<% end %>	
						<%= link_to edit_tweeeet_path(tweeet), class: "level-item" do%>
							<span class="icon"><i class="fa fa-pencil"></i></span>
						<% end %>	
						<%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
							<span class="icon"><i class="fa fa-trash-o"></i></span>
						<% end %>	

					</div>
				</nav>

			</div>
		</article>
	</div>
	<% end %>
		</div>
</div>
</div>
<%end%>

app/views/tweeeets/_form.html.erb
<%= simple_form_for(@tweeeet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    
    <%= f.input :tweeet, label: "What's interesting...", input_html:{class: "textarea"}, wrapper:false, label_html:{class: "label"}, placeholder:"Write something interesting" %> 
  </div>

</div>
 <%= f.button :submit, class: "button is-info" %> 

<% end %>

app/views/tweeeets/_homepagesignin.html.erb
<% if signed_in? %>
 <%= render 'trendsforyou' %> 
 <% else %>
  <div class="column is-one-third">
    <figure class="">
      <img src="https://abs.twimg.com/sticky/illustrations/twitter_login_sidebar_illustration.png" alt="homelogin" width="256" height="256">
    </figure>
    <div id="clearance" class="sign-in">
      <div class="">
      <i class="fa fa-twitter" ></i>
      <h2> Log in to Twitter</h2>
      </div>
      <br />
      <%= form_for :session, url: session_path do |form| %>
      <div class="">
        <div class="field">
          <%= form.label :Email%>
           <div class="control has-icons-left">
              <%= form.text_field :email, type: 'email' %>
            </div>
        </div>
        <div class="password-field">
          <%= form.label :password %>
          <div class="control has-icons-left">
              <%= form.password_field :password %>
          </div>
        </div>
        <br />
        <div>
          <div class="control">
          <button class="button is-info">Sign In</button>
          </div>
          <p> Or </p>
          <div class="button is-info">
          <% if Clearance.configuration.allow_sign_up? %>
            <%= link_to ("Sign Up"), sign_up_path%>
          <% end %>    
          </div> 
        </div>
  
        <% end %>
       
      </div>
  </div>
 </div>

<% end %>

app/views/tweeeets/_trends.html.erb
<div class="column">
	<% if signed_in? %>
	<div class="list is-hoverable ">
	  <a class="list-item ">
	    <i class="fa fa-home" ></i> <strong>Home</strong>
	  </a>
	  <a class="list-item">
	   <i class="fa fa-hashtag" ></i> <strong>Explore</strong>
	  </a>
	  <a class="list-item">
	   <i class="fa fa-bell" ></i>  <strong> Notifications</strong>
	  </a>
	  <a class="list-item">
	   <i class="fa fa-envelope" ></i> <strong>Messages</strong> 
	  </a>
	  <a class="list-item">
	   <i class="fa fa-bookmark" ></i> <STRONG>Bookmark</STRONG> 
	  </a>
	  <a class="list-item">
	    <i class="fa fa-list" ></i> <strong> Lists </strong>
	  </a>
	  <a class="list-item">
	   <i class="fa fa-user" ></i> <strong> Profile </strong> 
	  <a class="list-item">
	   <i class="fa fa-ellipsis-h" ></i> <strong> More </strong>
	  </a>
	  <a class="list-item">
	  	<% if signed_in? %>
	  	<%= link_to 'Tweeeet', new_tweeeet_path, class:"button is-info"%> 
    	<% end %>
     </a>
	</div>
	<div class = "box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64x64">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong> <%= current_user.name %></strong>
					<p>@<%= current_user.username %></p>
				</div>		
			</div> 
		</article><br />
		<% if signed_in? %>
      	<%= button_to 'Sign out', sign_out_path, method: :delete, class:"button is-info" %>
    	<% end %>
	
	</div>
	
	

	<%end%> 
	
</div>

app/views/tweeeets/_trendsforyou.html.erb
<div class="column">
	<% if signed_in? %>
	<nav class="panel">
		<p class="panel-heading">
			Trends For you
		</p>
		<a class="panel-block">
			<p> Trending in United States <br />
			 <strong>#planecrash</strong> <br />
			Trending with: Karachi, #PIACrash, Lahore <br />
			<div class="media-right">
				<figure class="image is-64x64">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
		</p>
		</a>
		<a class="panel-block">
			<p>Trending in OH <br />
			<strong>Glock</strong> <br />
			29.9K Tweets</p>
		</a>
		<a class="panel-block">
			<p>Politics Trending <br />
			<strong>#FocusOnTheTrumpDeathToll100K</strong> <br />
			21.3K Tweets</p>
		</a>
		<a class="panel-block">
			<p>Trending in United States <br />
			<strong>#meganfoxisfilipino</strong> <br />
			3,075 Tweets</p>
		</a>
		<a class="panel-block">
			Show more
		</a>

	</nav>
	
<%end%>


</div>

app/views/tweeeets/edit.html.erb
<h1>Editing Tweeeet</h1>

<%= render 'form', tweeeet: @tweeeet %>

<%= link_to 'Show', @tweeeet %> |
<%= link_to 'Back', tweeeets_path %>

app/views/tweeeets/index.html.erb
<section class="section">
  <div class="container">
  <div class="columns">
  	<% if signed_in? %>
    <%= render 'trends' %>
    <%= render 'feed' %>
    <%= render 'homepagesignin' %> 
    <%else%>
    <%= render 'feed' %>
    <%= render 'homepagesignin' %> 
  	<%end%>
  </div>
   
  </div>  
</section>

 

app/views/tweeeets/new.html.erb
<h1>New Tweeeet</h1>

<%= render 'form', tweeeet: @tweeeet %>

<%= link_to 'Back', tweeeets_path %>

app/views/tweeeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeeet_path(@tweeeet) %> |
<%= link_to 'Back', tweeeets_path %>

app/views/users/_form.html.erb
<div class="column">
	<div class="text-field">
		  <%= form.label :name %>
	  	  <%= form.text_field :name %>
	</div>
	<div class="text-field">
  		<%= form.label :username %>
  		<%= form.text_field :username %>
	</div>
	<div class="field">
	  <%= form.label :email %>
	  <%= form.text_field :email, type: 'email' %>
	</div>
	<div class="password-field">
	  <%= form.label :password %>
	  <%= form.password_field :password %>
	</div>
</div>

app/views/users/new.html.erb
<div class="column has-text-centered">
  <div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(". Already Signed up? sign_in"), sign_in_path %>
    </div>
  <% end %>
  </div>
</div>